# Generated by Django 6.0.4 on 2026-05-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('Burgers', 'Burgers'), ('Pizza', 'Pizza'), ('Drinks', 'Drinks'), ('Sides', 'Sides'), ('Desserts', 'Desserts')], default='Burgers', max_length=50),
        ),
    ]
